DOCKER_IMAGE_NAME=notifications-net-client

source environment.sh

docker run \
  --rm \
  -v "`pwd`:/var/project" \
  -e FUNCTIONAL_TESTS_API_HOST=${FUNCTIONAL_TESTS_API_HOST} \
  -e FUNCTIONAL_TESTS_SERVICE_API_TEST_KEY=${FUNCTIONAL_TESTS_SERVICE_API_TEST_KEY} \
  -e TEST_NUMBER=${TEST_NUMBER} \
  -e FUNCTIONAL_TEST_EMAIL=${FUNCTIONAL_TEST_EMAIL} \
  -e FUNCTIONAL_TEST_EMAIL_TEMPLATE_ID=${FUNCTIONAL_TEST_EMAIL_TEMPLATE_ID} \
  -e FUNCTIONAL_TEST_SMS_TEMPLATE_ID=${FUNCTIONAL_TEST_SMS_TEMPLATE_ID} \
  -e FUNCTIONAL_TEST_LETTER_TEMPLATE_ID=${FUNCTIONAL_TEST_LETTER_TEMPLATE_ID} \
  -e FUNCTIONAL_TESTS_SERVICE_EMAIL_REPLY_TO_ID=${FUNCTIONAL_TESTS_SERVICE_EMAIL_REPLY_TO_ID} \
  -e FUNCTIONAL_TESTS_SERVICE_SMS_SENDER_ID=${FUNCTIONAL_TESTS_SERVICE_SMS_SENDER_ID} \
  -e FUNCTIONAL_TESTS_SERVICE_API_KEY=${FUNCTIONAL_TESTS_SERVICE_API_KEY} \
  -e FUNCTIONAL_TESTS_SERVICE_API_TEST_KEY=${FUNCTIONAL_TESTS_SERVICE_API_TEST_KEY} \
  -it \
  ${DOCKER_IMAGE_NAME} \
  ${@}
